-- ============================================================================
-- KGK — feature_flags tábla (admin felületről kapcsolható szekciók)
-- ============================================================================
--
-- MIT CSINÁL
--   Létrehoz egy új táblát, amiben soronként EGY be/ki kapcsoló él. A publikus
--   oldal (script.js → loadFeatureFlags) ebből olvassa ki, hogy melyik szekciót
--   kell megjelenítenie; az admin felület (admin.html → „Szekciók" fül) pedig
--   ebben állítja át az `enabled` mezőt.
--
--   Három kapcsolóval indul, MINDHÁROM BEKAPCSOLVA — vagyis a futtatás után az
--   éles oldal pontosan ugyanúgy néz ki, mint előtte. Semmi nem tűnik el.
--
-- BŐVÍTÉS KÉSŐBB
--   Új kapcsolóhoz NEM kell új tábla és nem kell kódot módosítani az adminban:
--   elég egy új sort beszúrni (lásd a fájl végén az „ÚJ KAPCSOLÓ" mintát), és
--   a publikus HTML-ben a szekcióra rátenni a data-flag="<flag_key>" jelölőt.
--   Az admin lista magától kirajzolja az új sort is.
--
-- MIT NEM CSINÁL — FONTOS
--   * NINCS INSERT és NINCS DELETE policy. Ez SZÁNDÉKOS: a kapcsolók sorait
--     kizárólag SQL-ből hozzuk létre. Az admin felület csak az `enabled` mezőt
--     írja át, sort nem hoz létre és nem töröl. Így egy elkattintott gomb
--     soha nem tud kapcsolót eltüntetni. NE tegyél bele ilyen policy-t
--     később sem, hacsak nem szándékosan bővíted az admin jogosultságát.
--   * Nem nyúl egyetlen meglévő táblához vagy policy-hoz sem.
--
-- BIZTONSÁGI DÖNTÉSEK, AMIKET SZÁNDÉKOSAN ÍGY HOZTAM
--   1. Egyetlen tranzakció (BEGIN ... COMMIT). Ha bármelyik sor hibázik, az
--      EGÉSZ visszagördül — nem marad félkész tábla RLS nélkül, tehát nincs
--      olyan pillanat, amikor a tábla védtelenül állna.
--   2. `CREATE TABLE` — szándékosan `IF NOT EXISTS` NÉLKÜL. Ha a tábla már
--      létezik (pl. véletlenül másodszor futtatod), a script HANGOSAN elhasal
--      és visszagördül, ahelyett hogy csendben átugorná a létrehozást és
--      esetleg egy más felépítésű táblára rakná rá a policy-kat.
--   3. A policy-nevek a projekt eddigi mintáját követik:
--      „Public read <tábla>" az olvasásra, „Auth update <tábla>" az írásra
--      (lásd migrations/rls_modernize.sql és AUDIT_RLS.md).
--   4. Az írási policy `TO authenticated` — a natív, Postgres-szintű forma,
--      nem az elavult `auth.role() = 'authenticated'`. Ugyanaz, amire az
--      rls_modernize.sql migráció az összes többi táblát átállította.
--
-- HASZNÁLAT
--   Supabase Dashboard → SQL Editor → az egész fájl bemásolása → Run.
--   Utána futtasd le a fájl végén lévő ELLENŐRZŐ LEKÉRDEZÉSEKET.
--
-- Készült: 2026-08-26
-- ============================================================================


BEGIN;

-- ────────────────────────────────────────────────────────────────────────────
-- a) A TÁBLA
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE public.feature_flags (
    -- `by default as identity`: a Postgres adja az id-t, de kézzel is
    -- megadható, ha valaha egy adott sorszámra lenne szükség.
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- A kapcsoló gépi neve. Ez köti össze az adatbázist a HTML-lel:
    -- a publikus oldalon a data-flag="<flag_key>" jelölő hivatkozik rá.
    -- UNIQUE, hogy két azonos nevű kapcsoló ne kerülhessen be — olyankor
    -- kiszámíthatatlan lenne, melyik nyer.
    flag_key    text        NOT NULL UNIQUE,

    -- A tényleges kapcsoló. NOT NULL + DEFAULT true, mert a kód a hiányzó
    -- értéket „látszik"-ként értelmezi: egy null itt félreérthető lenne.
    enabled     boolean     NOT NULL DEFAULT true,

    -- Emberi nyelvű leírás — EZ jelenik meg az admin felületen a kapcsoló
    -- mellett. Ha üresen marad, az admin a flag_key-t mutatja helyette.
    label       text,

    updated_at  timestamptz NOT NULL DEFAULT now()
);


-- ────────────────────────────────────────────────────────────────────────────
-- b) RLS + POLICY-K
-- ────────────────────────────────────────────────────────────────────────────
ALTER TABLE public.feature_flags ENABLE ROW LEVEL SECURITY;

-- Olvasás: bárkinek. A publikus oldal anon kulccsal kéri le, enélkül a
-- látogató nem tudná eldönteni, mit kell megjelenítenie.
-- (A többi tábla publikus SELECT policy-ja is `TO public` — lásd AUDIT_RLS.md.)
CREATE POLICY "Public read feature_flags" ON public.feature_flags
    FOR SELECT TO public
    USING (true);

-- Írás: KIZÁRÓLAG bejelentkezett adminnak, és KIZÁRÓLAG meglévő sor
-- módosítása. Nincs INSERT és nincs DELETE policy — lásd a fejlécet.
CREATE POLICY "Auth update feature_flags" ON public.feature_flags
    FOR UPDATE TO authenticated
    USING (true)
    WITH CHECK (true);


-- ────────────────────────────────────────────────────────────────────────────
-- JOGOSULTSÁGOK (biztonsági háló)
-- ────────────────────────────────────────────────────────────────────────────
-- A Supabase alapból minden új public sémás táblára ad GRANT-ot az anon és
-- authenticated szerepnek, tehát ez a két sor jó eséllyel nem csinál semmit.
-- Azért van itt, hogy a tábla akkor is működjön, ha ezt az alapértelmezést
-- valaha megváltoztatnák.
--
-- FIGYELEM: a GRANT nem szűkít, csak bővít. Ha az alapértelmezett GRANT ALL
-- már lefutott, ez NEM veszi vissza a többletjogot — a védelmet továbbra is
-- a fenti RLS policy-k adják, nem ez a két sor. (AUDIT_RLS.md, K-2.)
GRANT SELECT ON public.feature_flags TO anon, authenticated;
GRANT UPDATE ON public.feature_flags TO authenticated;


-- ────────────────────────────────────────────────────────────────────────────
-- c) A HÁROM KEZDŐ KAPCSOLÓ — mindegyik BEKAPCSOLVA
-- ────────────────────────────────────────────────────────────────────────────
-- Azért indul mind `true`-val, hogy a bevezetés pillanatában az éles oldal
-- ne változzon semmit. Kikapcsolni utána, az admin felületről lehet.
--
-- Az ON CONFLICT azért van itt, hogy ha valaha egy sor már létezne, a script
-- ne hasaljon el rajta, és főleg NE írja vissza `true`-ra egy szándékosan
-- kikapcsolt kapcsolót.
INSERT INTO public.feature_flags (flag_key, enabled, label) VALUES
    ('golya_visible',      true, 'Gólya Kisokos szekció megjelenítése a főoldalon'),
    ('kapcsolat_visible',  true, 'Kapcsolatfelvételi form és „Írj nekünk" menüpont megjelenítése'),
    ('szponzorok_visible', true, 'Szponzorok szekció megjelenítése a főoldalon')
ON CONFLICT (flag_key) DO NOTHING;

COMMIT;


-- ============================================================================
-- ELLENŐRZŐ LEKÉRDEZÉSEK — futtasd le a COMMIT után
-- ============================================================================

-- 1) A három sornak kell megjelennie, mindhárom `enabled = true` értékkel.
SELECT id, flag_key, enabled, label FROM public.feature_flags ORDER BY id;

-- 2) Pontosan KÉT policy-nak kell lennie:
--      Public read feature_flags  | {public}         | SELECT
--      Auth update feature_flags  | {authenticated}  | UPDATE
--    INSERT és DELETE sor NEM lehet — ez így helyes, lásd a fejlécet.
SELECT policyname, roles, cmd
FROM pg_policies
WHERE schemaname = 'public' AND tablename = 'feature_flags'
ORDER BY cmd;

-- 3) Az RLS-nek bekapcsolva kell lennie (rowsecurity = true).
SELECT relname, relrowsecurity AS rowsecurity
FROM pg_class
WHERE oid = 'public.feature_flags'::regclass;


-- ============================================================================
-- ÚJ KAPCSOLÓ FELVÉTELE KÉSŐBB — minta, most ne futtasd
-- ============================================================================
-- Két lépés, kódmódosítás nélkül:
--
--   1. Ez az SQL (a szöveget írd át):
--
--      INSERT INTO public.feature_flags (flag_key, enabled, label) VALUES
--          ('rendezvenyek_visible', true, 'Rendezvények szekció megjelenítése a főoldalon');
--
--   2. Az index.html-ben a szekcióra tedd rá a jelölőt:
--
--      <section id="rendezvenyek" data-flag="rendezvenyek_visible"> ... </section>
--
--   Ha a szekció betöltés közben se villanhat fel, akkor a data-flag mellé
--   kell a class="flag-pending" is, és a szekció legelső gyerekeként egy
--   <div class="flag-skeleton"> ... </div> blokk — pontosan úgy, ahogy a
--   #golyaknak és a #szponzorok szekcióban már meg van csinálva.
--
--   Az admin „Szekciók" füle az új sort magától kirajzolja, ott nincs teendő.


-- ============================================================================
-- VISSZAÁLLÍTÁS — csak vészhelyzetre
-- ============================================================================
-- Ez TÖRLI a táblát a benne lévő kapcsolókkal együtt. A publikus oldal ettől
-- nem törik el: a script.js a hiányzó táblát úgy kezeli, hogy minden szekció
-- LÁTHATÓ marad. Az admin „Szekciók" füle üres állapotot mutat.
--
-- DROP TABLE public.feature_flags;
